name: Release
on:
  # Trigger the Action only on merge into main branch:
  # https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359
  push:
    branches:
      - main
      - master

jobs:
  tests:
    strategy:
      matrix:
        node-version:
          - 10
          - 12
          - 14
        os:
          - ubuntu-latest
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Install NodeJS ${{ matrix.node-version }}"
        uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node-version }}"
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
  release:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Update CHANGELOG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --generate-notes
      - name: Logging
        run: git status && git diff
      # - name: Commit any CHANGELOG.md changes
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add CHANGELOG.md
      #     if [[ -n "$(git status -s -- CHANGELOG.md)" ]]; then
      #       PACKAGE_VERSION=`node -e 'console.log(require("./package").version)'`
      #       RELEASE_MESSAGE="chore: update CHANGELOG.md after $PACKAGE_VERSION"
      #       git commit -m "$RELEASE_MESSAGE"
      #       git push
      #     fi
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
