name: Release
on:
  # Trigger the Action only on merge into main branch:
  # https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359
  push:
    branches:
      - main
      - master

jobs:
  tests:
    strategy:
      matrix:
        node-version:
          - 10
          - 12
          - 14
        os:
          - ubuntu-latest
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Install NodeJS ${{ matrix.node-version }}"
        uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node-version }}"
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
  release:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Logging
        run: git status && git diff
