name: Lint Commit Messages
on: [pull_request]

jobs:
  tests:
    strategy:
      matrix:
        node-version:
          - 10
          - 12
          - 14
        os:
          - ubuntu-latest
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Install NodeJS ${{ matrix.node-version }}"
        uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node-version }}"
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Logging
        cmd: git status && git diff
